import os
import streamlit as st

# from dotenv import load_dotenv
# load_dotenv()

# MISTRAL_ITINERARY_KEY = os.getenv("MISTRAL_ITINERARY_KEY")
# MISTRAL_TRANSPORT_KEY = os.getenv("MISTRAL_TRANSPORT_KEY")
# MISTRAL_STAY_KEY = os.getenv("MISTRAL_STAY_KEY")
# MISTRAL_FOOD_KEY = os.getenv("MISTRAL_FOOD_KEY")
# MISTRAL_PLACES_KEY = os.getenv("MISTRAL_PLACES_KEY")

MISTRAL_ITINERARY_KEY = st.secrets.MISTRAL_ITINERARY_KEY
MISTRAL_TRANSPORT_KEY = st.secrets.MISTRAL_TRANSPORT_KEY
MISTRAL_STAY_KEY = st.secrets.MISTRAL_STAY_KEY
MISTRAL_FOOD_KEY = st.secrets.MISTRAL_FOOD_KEY
MISTRAL_PLACES_KEY = st.secrets.MISTRAL_PLACES_KEY